### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by SirJohnDoe** [f0e/letterboxd-trakt-sync#1]
I've been using this script for a couple months now (thanks!) and it's been working great until recently.

The logging shows the following error: 

> letterboxd-trakt-sync  | Started script
> letterboxd-trakt-sync  | Traceback (most recent call last):
> letterboxd-trakt-sync  |   File "<frozen runpy>", line 198, in _run_module_as_main
> letterboxd-trakt-sync  |   File "<frozen runpy>", line 88, in _run_code
> letterboxd-trakt-sync  |   File "/app/letterboxd_trakt/main.py", line 22, in <module>
> letterboxd-trakt-sync  |     run()
> letterboxd-trakt-sync  |   File "/app/letterboxd_trakt/main.py", line 18, in run
> letterboxd-trakt-sync  |     sync_letterboxd_diary(config, account)
> letterboxd-trakt-sync  |   File "/app/letterboxd_trakt/sync.py", line 233, in sync_letterboxd_diary
> letterboxd-trakt-sync  |     lb_diary_to_process = get_diary(lb_user, account.internal.last_letterboxd_diary_entry)
> letterboxd-trakt-sync  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> letterboxd-trakt-sync  |   File "/app/letterboxd_trakt/sync.py", line 205, in get_diary
> letterboxd-trakt-sync  |     lb_page_diary_entries: dict[str, dict] = LB_user.user_diary(lb_user, page=page)["entrys"]
> letterboxd-trakt-sync  |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> letterboxd-trakt-sync  | TypeError: 'module' object is not callable

When I roll back to an older version (e.g. from 5 months back), I get a 'KeyError: 'data-film-run-time' error.

My letterboxd diary/profile is still public, so not sure what the issue is.

**Comment by f0e** [comment]
Thanks for the report, looks like Letterboxd changed some stuff and the library I use for fetching the diary hasn't updated yet. I forked it and updated it myself so it should be good now, but let me know if it's still erroring.

**Comment by SirJohnDoe** [comment]
Thank you, it is working fine again!
